scales/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

app_name = 'scales_app'

urlpatterns = [
    path('scales/', include('scales_app.urls')),
    path('admin/', admin.site.urls),
]

scales_app/urls.py
from django.urls import path

from . import views

app_name = 'scales_app'

urlpatterns = [
    path('SelectBoard', views.SelectBoard, name='SelectBoard'),
    path('GenBoard', views.GenBoard, name='GenBoard'),
               ]

scales_app/models.py
from django.db import models

# Create your models here.

class Fretboard(models.Model):

    # User specifies the particular major scale they would like.
    scale = models.CharField(max_length=3)

    # User specifies the tuning of each string on their guitar.
    #Largest diameter string is string 1. A traditionally tunded guitar would be as follows 1=E, 2=A, 3=D, 4=G, 5=B, 6=E

    string1 = models.CharField(max_length=3)
    string2 = models.CharField(max_length=3)
    string3 = models.CharField(max_length=3)
    string4 = models.CharField(max_length=3)
    string5 = models.CharField(max_length=3)
    string6 = models.CharField(max_length=3)

scales_app/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.views import generic
from PIL import Image

from scales1 import scales
from .models import Fretboard

#scale = 'F'
#tunings = ['E', 'A', 'D', 'G', 'B', 'E']


def SelectBoard(request):
    #model = Fretboard
    return render(request, 'scales_app/select_board.html')

def GenBoard(request):
    fretboard = request.POST

    img_scale = 1

    size = (int(1080*img_scale),int(200*img_scale))

    #print(fretboard)

    tunings = []

    scale = fretboard['scale']

    tunings.append(fretboard['string1'])
    tunings.append(fretboard['string2'])
    tunings.append(fretboard['string3'])
    tunings.append(fretboard['string4'])
    tunings.append(fretboard['string5'])
    tunings.append(fretboard['string6'])

    img = scales.gen_board(scale, tunings)
    img = img.resize(size)

    response = HttpResponse(content_type = "image/bmp")
    img.save(response, "BMP")
    return response

    #return HttpResponseRedirect(reverse('scales_app:SelectBoard'))

scales_app/templates/scales_app/board_web.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



</body>
</html>

scales_app/templates/scales_app/select_board.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="/scales/scales_app/templates/scales_app/scales.css">
    <meta charset="UTF-8">
    <title>Guitar Fretboard Generator</title>
</head>
<h1>Guitar Fretboard Generator</h1>

<body>
<form action="{% url 'scales_app:GenBoard' %}" method="post">
    {% csrf_token %}
    <div class="scale">
        <strong>Select Major Scale:</strong>
        <select name="scale">
            <option value="C">C</option>
            <option value="G">G</option>
            <option value="D">D</option>
            <option value="A">A</option>
            <option value="E">E</option>
            <option value="B">B</option>
            <option value="F#">F#</option>
            <option value="C#">C#</option>
            <option value="F">F</option>
            <option value="Bb">Bb</option>
            <option value="Eb">Eb</option>
            <option value="Ab">Ab</option>
        </select>
        <hr class = "lineStyle">
    </div>

    <div class = "string">
        <label class="string">String 1 tuning:</label>
        <select name="string1" id="string1" value="">
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="F#">F#</option>
                <option value="G">G</option>
                <option value="G#">G#</option>
                <option value="A">A</option>
                <option value="Bb">Bb</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="C#">C#</option>
                <option value="D">D</option>
                <option value="D#">D#</option>
                <option value="Eb">Eb</option>
                <option value="Ab">Ab</option>
        </select>
    </div>
    <br>


    <div class = "string">
        <label>String 2 tuning:</label>
        <select name="string2" id="string2" value="">
                <option value="A">A</option>
                <option value="Bb">Bb</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="C#">C#</option>
                <option value="D">D</option>
                <option value="D#">D#</option>
                <option value="Eb">Eb</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="F#">F#</option>
                <option value="G">G</option>
                <option value="G#">G#</option>
                <option value="Ab">Ab</option>
        </select>
    </div>
    <br>

    <div class ="string">
        <label>String 3 tuning:</label>
        <select name="string3" id="string3" value="">
                <option value="D">D</option>
                <option value="D#">D#</option>
                <option value="Eb">Eb</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="F#">F#</option>
                <option value="G">G</option>
                <option value="G#">G#</option>
                <option value="Ab">Ab</option>
                <option value="A">A</option>
                <option value="Bb">Bb</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="C#">C#</option>
        </select>
    </div>
    <br>

    <div class = "string">
        <label>String 4 tuning:</label>
        <select name="string4" id="string4" value="">
                <option value="G">G</option>
                <option value="G#">G#</option>
                <option value="Ab">Ab</option>
                <option value="A">A</option>
                <option value="Bb">Bb</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="C#">C#</option>
                <option value="D">D</option>
                <option value="D#">D#</option>
                <option value="Eb">Eb</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="F#">F#</option>
        </select>
    </div>
    <br>

    <div class = "string">
        <label>String 5 tuning:</label>
        <select name="string5" id="string5" value="">
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="C#">C#</option>
                <option value="D">D</option>
                <option value="D#">D#</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="F#">F#</option>
                <option value="G">G</option>
                <option value="G#">G#</option>
                <option value="A">A</option>
                <option value="Bb">Bb</option>
                <option value="Eb">Eb</option>
                <option value="Ab">Ab</option>
        </select>
    </div>
    <br>

    <div class = "string6">
        <label>String 6 tuning:</label>
        <select name="string6" id="string6" value="">
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="F#">F#</option>
                <option value="G">G</option>
                <option value="G#">G#</option>
                <option value="A">A</option>
                <option value="Bb">Bb</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="C#">C#</option>
                <option value="D">D</option>
                <option value="D#">D#</option>
                <option value="Eb">Eb</option>
                <option value="Ab">Ab</option>
        </select>
    </div>
    <br>
    <input type="submit" value="Generate Board">
    <hr class = "lineStyle">

</form>
Use Notes: If a scale that contains flats (F, Bb, Eb, Ab) <br> is chosen, the string tunings must not contain any sharps.
</body>
</html>